services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: yugioh
      POSTGRES_PASSWORD: yugioh
      POSTGRES_DB: yugiohdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: